mysql_flamenco:
  image: mysql
  container_name: mysql_flamenco
  ports:
   - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=root
flamenco_server:
  image: armadillica/flamenco_server_dev
  container_name: flamenco_server
  ports:
   - "9999:9999"
  volumes:
   - /FLAMENCO_GIT_CHECKOUT/flamenco/server:/data/git/server
   - /STORAGE_PATH/storage/shared:/data/storage/shared
   - /STORAGE_PATH/storage/server:/data/storage/server
  links:
   - mysql_flamenco:mysql_flamenco
flamenco_manager:
  image: armadillica/flamenco_manager_dev
  container_name: flamenco_manager
  ports:
   - "7777:7777"
  volumes:
   - /FLAMENCO_GIT_CHECKOUT/flamenco/manager:/data/git/manager
   - /STORAGE_PATH/storage/shared:/data/storage/shared
   - /STORAGE_PATH/storage/manager:/data/storage/manager
  links:
   - mysql_flamenco:mysql_flamenco
   - flamenco_server:flamenco_server
flamenco_dashboard:
  image: armadillica/flamenco_dashboard_dev
  container_name: flamenco_dashboard
  ports:
   - "8888:8888"
  volumes:
   - /FLAMENCO_GIT_CHECKOUT/flamenco/dashboard:/data/git/dashboard
   - /STORAGE_PATH/storage/shared:/data/storage/shared
   - /STORAGE_PATH/flamenco_data/storage/dashboard:/data/storage/dashboard

